version: "3"
services:
  invite:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/src/app:ro
      - /node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://root:example@mongo:27017

    command: npm run dev


